import logging
import time
from typing import Any, Optional

from langchain_google_genai import ChatGoogleGenerativeAI

from .base_client import BaseLLMClient
from .validators import validate_model

logger = logging.getLogger(__name__)

# Retry settings for transient Gemini errors (429 / 503)
_MAX_RETRIES = 5
_BASE_DELAY = 5  # seconds

# Fallback chain: when all retries fail on primary model, try the next model.
# Ordered from most capable → least capable within each family.
_FALLBACK_CHAINS = {
    "gemini-2.5-pro": ["gemini-3-flash-preview", "gemini-2.5-flash", "gemini-2.5-flash-lite"],
    "gemini-2.5-flash": ["gemini-3-flash-preview", "gemini-2.5-flash-lite"],
    "gemini-3-flash-preview": ["gemini-2.5-flash", "gemini-2.5-flash-lite"],
    "gemini-3.1-pro-preview": ["gemini-3-flash-preview", "gemini-2.5-flash"],
    "gemini-3.1-flash-lite-preview": ["gemini-2.5-flash-lite"],
}


def _is_retryable(err: str) -> bool:
    return (
        "429" in err
        or "RESOURCE_EXHAUSTED" in err
        or "503" in err
        or "UNAVAILABLE" in err
        or "499" in err
        or "CANCELLED" in err
    )


# Models that use extended thinking and may need a longer default timeout.
# langchain_google_genai defaults timeout=None which maps to httpx's default
# of ~5s read timeout — far too short for thinking-enabled requests.
_LONG_TIMEOUT_MODELS = {"gemini-3.1-pro-preview", "gemini-3-flash-preview"}
_DEFAULT_THINKING_TIMEOUT = 300  # seconds


class NormalizedChatGoogleGenerativeAI(ChatGoogleGenerativeAI):
    """ChatGoogleGenerativeAI with normalized content output, retry, and model fallback.

    Gemini 3 models return content as list: [{'type': 'text', 'text': '...'}]
    This normalizes to string for consistent downstream handling.

    On transient errors (429/503), retries with exponential backoff. If all
    retries fail, falls back to a less-loaded model from the fallback chain
    and warns the user.
    """

    def _normalize_content(self, response):
        content = response.content
        if isinstance(content, list):
            texts = [
                item.get("text", "") if isinstance(item, dict) and item.get("type") == "text"
                else item if isinstance(item, str) else ""
                for item in content
            ]
            response.content = "\n".join(t for t in texts if t)
        return response

    def _try_invoke(self, call, *args, **kwargs):
        """Try invoking with exponential backoff. Returns response or raises."""
        last_err = None
        for attempt in range(_MAX_RETRIES):
            try:
                return call(*args, **kwargs)
            except Exception as e:
                last_err = e
                if _is_retryable(str(e)):
                    delay = _BASE_DELAY * (2 ** attempt)
                    logger.warning(
                        "Gemini transient error (attempt %d/%d), retrying in %ds: %s",
                        attempt + 1, _MAX_RETRIES, delay, str(e)[:120],
                    )
                    time.sleep(delay)
                else:
                    raise
        raise last_err

    def invoke(self, input, config=None, **kwargs):
        # Try primary model first
        try:
            return self._normalize_content(
                self._try_invoke(super().invoke, input, config, **kwargs)
            )
        except Exception as primary_err:
            if not _is_retryable(str(primary_err)):
                raise

        # Primary model exhausted retries — try fallback chain
        primary_model = self.model
        fallbacks = _FALLBACK_CHAINS.get(primary_model, [])

        if not fallbacks:
            logger.error(
                "All %d retries failed for %s and no fallback models available.",
                _MAX_RETRIES, primary_model,
            )
            raise primary_err

        for fallback_model in fallbacks:
            logger.warning(
                "⚠ %s unavailable after %d retries. Falling back to %s "
                "(analysis quality may be reduced).",
                primary_model, _MAX_RETRIES, fallback_model,
            )
            try:
                # Build a fresh LLM instance with the fallback model
                fallback_kwargs = {
                    k: v for k, v in self.__dict__.items()
                    if k in ("temperature", "max_tokens", "top_p", "top_k", "n")
                    and v is not None
                }
                fallback_llm = ChatGoogleGenerativeAI(
                    model=fallback_model, **fallback_kwargs
                )
                response = self._try_invoke(
                    fallback_llm.invoke, input, config, **kwargs
                )
                # Tag the response so downstream can detect the fallback
                warning = (
                    f"\n\n---\n⚠ **Model fallback:** This response was generated by "
                    f"`{fallback_model}` because `{primary_model}` was unavailable. "
                    f"Analysis quality may differ from expected."
                )
                self._normalize_content(response)
                response.content += warning
                return response
            except Exception as e:
                if _is_retryable(str(e)):
                    logger.warning(
                        "Fallback model %s also unavailable, trying next...",
                        fallback_model,
                    )
                    continue
                raise

        # All fallbacks exhausted
        logger.error(
            "All models exhausted (primary: %s, fallbacks: %s). Giving up.",
            primary_model, fallbacks,
        )
        raise primary_err


class GoogleClient(BaseLLMClient):
    """Client for Google Gemini models."""

    def __init__(self, model: str, base_url: Optional[str] = None, **kwargs):
        super().__init__(model, base_url, **kwargs)

    def get_llm(self) -> Any:
        """Return configured ChatGoogleGenerativeAI instance."""
        llm_kwargs = {"model": self.model}

        for key in ("timeout", "max_retries", "google_api_key", "callbacks", "http_client", "http_async_client"):
            if key in self.kwargs:
                llm_kwargs[key] = self.kwargs[key]

        # Thinking-enabled models can take several minutes; ensure a generous
        # default timeout so the client doesn't cancel the request (499) before
        # the server has time to finish. Callers can still override via kwargs.
        if "timeout" not in llm_kwargs and self.model in _LONG_TIMEOUT_MODELS:
            llm_kwargs["timeout"] = _DEFAULT_THINKING_TIMEOUT

        # Map thinking_level to appropriate API param based on model
        # Gemini 3 Pro: low, high
        # Gemini 3 Flash: minimal, low, medium, high
        # Gemini 2.5: thinking_budget (0=disable, -1=dynamic)
        thinking_level = self.kwargs.get("thinking_level")
        model_lower = self.model.lower()
        if "gemini-3" in model_lower:
            # Gemini 3 thinking models REQUIRE an explicit thinking_level for tool
            # calling to work correctly (the API needs thought_signature handling).
            # Default to "low" when the caller doesn't specify — "low" gives the
            # fastest latency while still enabling proper thinking/tool-call flow.
            if not thinking_level:
                thinking_level = "low"
            # Gemini 3 Pro doesn't support "minimal", coerce to "low"
            if "pro" in model_lower and thinking_level == "minimal":
                thinking_level = "low"
            llm_kwargs["thinking_level"] = thinking_level
        elif thinking_level:
            # Gemini 2.5: map to thinking_budget
            llm_kwargs["thinking_budget"] = -1 if thinking_level == "high" else 0

        return NormalizedChatGoogleGenerativeAI(**llm_kwargs)

    def validate_model(self) -> bool:
        """Validate model for Google."""
        return validate_model("google", self.model)
